server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctor-service/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient-service/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient-service/**

