eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8087
spring:
  application:
    name: service-schedules
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/agendamento_consultas?useTimezone=true&serverTimezone=UTC
    username: user
    password: user

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
